"""ai settings

Revision ID: 028ddd3eccf2
Revises: d106c71cdeb5
Create Date: 2026-06-21 09:15:21.770873
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '028ddd3eccf2'
down_revision: Union[str, None] = 'd106c71cdeb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('llm_model', sa.String(length=80), nullable=False),
    sa.Column('embedding_model', sa.String(length=80), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('api_key_last4', sa.String(length=8), nullable=True),
    sa.Column('monthly_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_message', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_ai_setting_org')
    )
    op.create_index(op.f('ix_ai_settings_organization_id'), 'ai_settings', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_settings_organization_id'), table_name='ai_settings')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
