"""ethics kpi reward

Revision ID: 9b1ed884e836
Revises: 028ddd3eccf2
Create Date: 2026-06-21 09:47:42.794608
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9b1ed884e836'
down_revision: Union[str, None] = '028ddd3eccf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ethics_applications',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('applicant_id', sa.UUID(), nullable=True),
    sa.Column('review_type', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('involves_human_subjects', sa.Boolean(), nullable=False),
    sa.Column('involves_sensitive_data', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_ethics_code')
    )
    op.create_index(op.f('ix_ethics_applications_organization_id'), 'ethics_applications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ethics_applications_status'), 'ethics_applications', ['status'], unique=False)
    op.create_table('kpi_rule_versions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('expression_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_rule_versions_organization_id'), 'kpi_rule_versions', ['organization_id'], unique=False)
    op.create_table('kpi_runs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=True),
    sa.Column('rule_hash', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_runs_organization_id'), 'kpi_runs', ['organization_id'], unique=False)
    op.create_table('reward_applications',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=True),
    sa.Column('output_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_reward_code')
    )
    op.create_index(op.f('ix_reward_applications_organization_id'), 'reward_applications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reward_applications_status'), 'reward_applications', ['status'], unique=False)
    op.create_table('ethics_decisions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['ethics_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ethics_decisions_application_id'), 'ethics_decisions', ['application_id'], unique=False)
    op.create_index(op.f('ix_ethics_decisions_organization_id'), 'ethics_decisions', ['organization_id'], unique=False)
    op.create_table('ethics_reviews',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('recommendation', sa.String(length=30), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['ethics_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ethics_reviews_application_id'), 'ethics_reviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_ethics_reviews_organization_id'), 'ethics_reviews', ['organization_id'], unique=False)
    op.create_table('kpi_contributions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('researcher_id', sa.UUID(), nullable=True),
    sa.Column('researcher_name', sa.String(length=255), nullable=True),
    sa.Column('output_id', sa.UUID(), nullable=True),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['kpi_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_contributions_organization_id'), 'kpi_contributions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_kpi_contributions_run_id'), 'kpi_contributions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_contributions_run_id'), table_name='kpi_contributions')
    op.drop_index(op.f('ix_kpi_contributions_organization_id'), table_name='kpi_contributions')
    op.drop_table('kpi_contributions')
    op.drop_index(op.f('ix_ethics_reviews_organization_id'), table_name='ethics_reviews')
    op.drop_index(op.f('ix_ethics_reviews_application_id'), table_name='ethics_reviews')
    op.drop_table('ethics_reviews')
    op.drop_index(op.f('ix_ethics_decisions_organization_id'), table_name='ethics_decisions')
    op.drop_index(op.f('ix_ethics_decisions_application_id'), table_name='ethics_decisions')
    op.drop_table('ethics_decisions')
    op.drop_index(op.f('ix_reward_applications_status'), table_name='reward_applications')
    op.drop_index(op.f('ix_reward_applications_organization_id'), table_name='reward_applications')
    op.drop_table('reward_applications')
    op.drop_index(op.f('ix_kpi_runs_organization_id'), table_name='kpi_runs')
    op.drop_table('kpi_runs')
    op.drop_index(op.f('ix_kpi_rule_versions_organization_id'), table_name='kpi_rule_versions')
    op.drop_table('kpi_rule_versions')
    op.drop_index(op.f('ix_ethics_applications_status'), table_name='ethics_applications')
    op.drop_index(op.f('ix_ethics_applications_organization_id'), table_name='ethics_applications')
    op.drop_table('ethics_applications')
    # ### end Alembic commands ###
